### PR TITLE
Styles refresh 2018 additions and custom style removals

### PR DESCRIPTION
**Pull request by guerler**
This PR removes several custom style classes and uses existing or default bootstrap styles instead. It is part of a larger PR I have been working on recently, containing smaller and better separated changesets.

### CODE REVIEW

**Comment by jxtx** [comment]
@guerler is it worth trying to fix the tests failing due to selector changes?

**Comment by guerler** [comment]
@jxtx its worth trying, I removed the backbone label wrapper since we did not really use it. I will try to remove the corresponding test too. Right now its cumbersome to work with qunit tests since they do not work locally but its worth a try.

**Comment by guerler** [comment]
@galaxybot test this.

**Comment by guerler** [comment]
Tests are fixed now.

**Pull request merged**
